(() => {
  const translations = {
    en: {
      converter: 'Converter',
      voiceRecorder: 'Voice recorder',
      durationCalculator: 'Duration calculator',
      iosGuideNavigation: 'Guide page',
      converterPageTitle: 'M4A and MP3 to WAV',
      recorderPageTitle: 'Voice recorder',
      durationPageTitle: 'WAV Duration Ledger',
      iosGuidePageTitle: 'iPhone Voice Memos Guide',
      errorPageLabel: 'ERROR 404',
      errorPageTitle: 'This page went quiet.',
      errorPageText: 'The page you are looking for does not exist or has moved.',
      errorPageBack: 'Back to converter',
      toggleLanguage: 'Toggle language',
      openNavigation: 'Open navigation',
      audioConverter: 'Audio converter',
      converterTitle: 'Convert audio for every workflow.',
      converterTitleAccent: 'M4A and MP3 to WAV.',
      converterLede: 'Create high-quality WAV files in your browser. Fast, private, and processed entirely on your device.',
      dropTitle: 'Drop your audio here',
      selectedAudio: 'audio file selected',
      selectedAudioPlural: 'audio files selected',
      queue: 'QUEUE',
      selectedAudioLabel: 'SELECTED AUDIO',
      files: 'files',
      file: 'file',
      dropPrompt: 'or upload a parent folder',
      chooseFiles: 'Choose files',
      uploadFolder: 'Upload folder',
      outputFormat: 'OUTPUT FORMAT',
      filenamePrefix: 'FILENAME PREFIX',
      prefixNote: 'Added before each WAV filename',
      convertToWav: 'Convert to WAV',
      toWav: 'to WAV',
      supportedFormats: 'M4A or MP3',
      maxEach: 'MAX 500 MB EACH',
      readyToDownload: 'READY TO DOWNLOAD',
      convertedAudio: 'Converted audio',
      downloadAll: 'Download all',
      chooseAudio: 'Drop M4A or MP3 files',
      recorderLabel: 'VOICE RECORDER',
      recorderTitle: 'Give your voice a file.',
      recorderLede: 'Record from your microphone and download a clean MP3. Everything stays in this browser.',
      voiceRecorderRegion: 'Voice recorder',
      readyToRecord: 'Ready to record',
      startRecording: 'Start recording',
      stopRecording: 'Stop recording',
      start: 'Start recording',
      stop: 'Stop recording',
      creatingMp3: 'Creating MP3...',
      recordingReady: 'RECORDING READY',
      downloadMp3: 'Download MP3',
      micPermissionNote: 'Your microphone stays private and local.',
      microphoneDenied: 'Microphone access was not granted. Check your browser permissions and try again.',
      recordingUnsupported: 'This browser cannot record audio. Try a current version of Chrome, Edge, Safari, or Firefox.',
      recordingFailed: 'The recording could not be converted to MP3.',
      filenameLabel: 'FILENAME',
      editFilename: 'Edit filename',
      audioToolsNavigation: 'Audio tools navigation',
      closeMessage: 'Close message',
      removeFile: 'Remove',
      removeSelectedFiles: 'Remove selected files',
      prefixPlaceholder: 'Optional, e.g. khm_EBC_',
      chooseFolderRegion: 'Choose a folder',
      audioSummary: 'Audio summary',
      nonWavFiles: 'Non-WAV files',
      convertAllToWav: 'Convert all to WAV',
      exportCsvTitle: 'Export readable WAV results as CSV',
      selectWavFilesFromFiles: 'Select one or more WAV files from the Files app.',
      selectAudioFilesFromFiles: 'In Voice Memos, use Share > Save to Files, then select the M4A or MP3 file here.',
      iosGuideLabel: 'IPHONE GUIDE',
      iosGuideTitle: 'Move your Voice Memos recording to Files',
      iosGuideText: 'In Voice Memos, select your recording, tap Share, choose Save to Files, and save it in a folder you can find again.',
      iosGuideButton: 'Choose from Files',
      iosGuideStepOne: '1. Tap Share',
      iosGuideStepTwo: '2. Choose Save to Files',
      iosGuideSteps: 'iPhone Voice Memos steps',
      iosGuideStepOneText: 'Open the recording in Voice Memos and tap Share.',
      iosGuideStepTwoText: 'Save the audio in a folder you can find from Files.',
      iosGuideStepThree: '3. Create a new folder',
      iosGuideStepThreeText: 'Tap New Folder in the Files save screen.',
      iosGuideStepFour: '4. Name a folder',
      iosGuideStepFourText: 'Enter a name for the new folder.',
      iosGuideStepFive: '5. Open that folder',
      iosGuideStepFiveText: 'Tap the folder you just created.',
      iosGuideStepSix: '6. Save the audio in that folder',
      iosGuideStepSixText: 'Tap Save to finish saving the recording there.',
      iosGuideReady: 'When the recording is saved, choose it here.',
      iosGuideBack: 'Back to converter',
      openingConverter: 'Opening converter...',
      clearFiles: 'Remove selected files',
      audioTools: 'AUDIO TOOLS',
      ffmpegLocal: 'LOCAL PROCESSING · FFMPEG.WASM',
      addedBefore: 'Added before each WAV filename',
      durationTitle: 'Measure your audio library.',
      durationLede: 'Scan a folder to calculate the total duration of every WAV recording, including files in nested folders.',
      selectFolder: 'Select your parent folder',
      privacyNote: 'Your files stay on this device. Nothing is sent anywhere.',
      dropWavFiles: 'Drop WAV files here',
      chooseFolder: 'Choose folder',
      totalDuration: 'Total duration',
      successfulWav: 'Successful WAV files',
      unsuccessfulFiles: 'Unsuccessful files',
      shortestFile: 'Shortest file',
      longestFile: 'Longest file',
      totalSize: 'Total size',
      fileLedger: 'File ledger',
      noFilesScanned: 'No files scanned',
      exportCsv: 'Export CSV',
      emptyLedger: 'Choose a folder to see its WAV files here.',
      showNonWav: 'Show non-WAV files',
      hideNonWav: 'Hide non-WAV files',
      convertAll: 'Convert all',
      scanComplete: 'Scan complete. All WAV files were read locally.',
      noWavFound: 'No WAV files found in that folder.',
      localProcessing: 'LOCAL PROCESSING',
      downloaded: 'Downloaded',
      tryAgain: 'Try again',
      download: 'Download',
      packaging: 'Packaging...',
      converting: 'Converting...',
      loadingFfmpeg: 'Loading FFmpeg for file',
      conversionComplete: 'Conversion complete',
      conversionCompleteSkipped: 'Conversion complete with skipped files',
      skipped: 'Skipped',
      conversionFailed: 'Conversion failed',
      noFilesConverted: 'No files could be converted. Check the selected audio files.',
      tooLarge: 'is larger than the 500 MB limit.',
      chooseSupported: 'Please choose M4A or MP3 files.',
      unsupportedFiles: 'Unsupported files ignored',
      moreFiles: 'more',
      unableFolder: 'Unable to read that folder.',
      showAllFiles: 'Show all files',
      hideAllFiles: 'Hide all files',
      packageFailed: 'Could not package the converted files.',
      couldNotConvert: 'could not be converted.',
      fileHeader: 'File',
      durationHeader: 'Duration',
      reading: 'Reading...',
      couldNotRead: 'Could not read',
      waitingFolder: 'Waiting for a folder.',
      readableOf: 'readable of',
      wavFile: 'WAV file',
      restored: 'Restored',
      exported: 'Exported',
      unreadable: 'unreadable file',
      ready: 'ready',
      fromBrowser: 'from this browser',
      result: 'result',
      results: 'results',
      estimatedFor: 'Estimated time for',
      recommendedBatch: 'Suggested batch',
      estimatedTime: 'about',
      remaining: 'remaining',
      complete: 'complete'
    },
    kh: {
      converter: 'បម្លែងសំឡេង',
      voiceRecorder: 'ថតសំឡេង',
      durationCalculator: 'គណនារយៈពេល',
      iosGuideNavigation: 'ការណែនាំលើ iPhone',
      converterPageTitle: 'បម្លែង M4A និង MP3 ទៅជា WAV',
      durationPageTitle: 'តារាងគណនារយៈពេល WAV',
      recorderPageTitle: 'កម្មវិធីថតសំឡេង',
      iosGuidePageTitle: 'ការណែនាំ Voice Memos លើ iPhone',
      errorPageLabel: 'កំហុស 404',
      errorPageTitle: 'រកមិនឃើញទំព័រនេះឡើយ',
      errorPageText: 'ទំព័រដែលអ្នកកំពុងស្វែងរកមិនមាន ឬត្រូវបានផ្លាស់ប្តូរទីតាំង។',
      errorPageBack: 'ត្រឡប់ទៅទំព័រដើម',
      toggleLanguage: 'ប្តូរភាសា',
      openNavigation: 'បើកម៉ឺនុយ',
      audioConverter: 'កម្មវិធីបម្លែងសំឡេង',
      converterTitle: 'បម្លែងឯកសារសំឡេងយ៉ាងងាយស្រួល។',
      converterTitleAccent: 'ពី M4A និង MP3 ទៅជា WAV។',
      converterLede: 'បង្កើតឯកសារ WAV កម្រិតច្បាស់ផ្ទាល់លើកម្មវិធីរុករក (Browser)។ លឿន មានសុវត្ថិភាព និងមិនបង្ហោះឯកសារចេញក្រៅឡើយ។',
      dropTitle: 'ទម្លាក់ឯកសារសំឡេងនៅទីនេះ',
      selectedAudio: 'ឯកសារសំឡេងដែលបានជ្រើសរើស',
      selectedAudioPlural: 'ឯកសារសំឡេងដែលបានជ្រើសរើស',
      queue: 'បញ្ជីរង់ចាំបម្លែង',
      selectedAudioLabel: 'សំឡេងដែលបានជ្រើសរើស',
      files: 'ឯកសារ',
      file: 'ឯកសារ',
      dropPrompt: 'ឬជ្រើសរើសថតផ្ទុកឯកសារ (Folder)',
      chooseFiles: 'ជ្រើសរើសឯកសារ',
      uploadFolder: 'ជ្រើសរើសថត (Folder)',
      outputFormat: 'ទម្រង់ឯកសារចេញ',
      filenamePrefix: 'បុព្វបទឈ្មោះ (Prefix)',
      prefixNote: 'បន្ថែមនៅខាងមុខឈ្មោះឯកសារ WAV',
      convertToWav: 'បម្លែងទៅជា WAV',
      toWav: 'ទៅជា WAV',
      supportedFormats: 'គាំទ្រ M4A ឬ MP3',
      maxEach: 'ទំហំធំបំផុត 500 MB ក្នុងមួយឯកសារ',
      readyToDownload: 'រួចរាល់សម្រាប់ទាញយក',
      convertedAudio: 'ឯកសារដែលបានបម្លែងរួច',
      downloadAll: 'ទាញយកទាំងអស់ (ZIP)',
      chooseAudio: 'ទម្លាក់ឯកសារ M4A ឬ MP3 នៅទីនេះ',
      recorderLabel: 'កម្មវិធីថតសំឡេង',
      recorderTitle: 'ថតសំឡេង និងរក្សាទុកជា MP3។',
      recorderLede: 'ថតសំឡេងតាមរយៈមីក្រូហ្វូន ហើយទាញយកជាឯកសារ MP3 ដោយផ្ទាល់ក្នុងកម្មវិធីរុករក។',
      voiceRecorderRegion: 'ផ្ទាំងថតសំឡេង',
      readyToRecord: 'រួចរាល់ក្នុងការថត',
      startRecording: 'ចាប់ផ្តើមថត',
      stopRecording: 'បញ្ឈប់ការថត',
      start: 'ចាប់ផ្តើមថត',
      stop: 'បញ្ឈប់ការថត',
      creatingMp3: 'កំពុងបង្កើតឯកសារ MP3...',
      recordingReady: 'ការថតបានរួចរាល់',
      downloadMp3: 'ទាញយក MP3',
      micPermissionNote: 'សំឡេងរបស់អ្នកមានសុវត្ថិភាព និងដំណើរការតែក្នុងឧបករណ៍របស់អ្នកប៉ុណ្ណោះ។',
      microphoneDenied: 'មិនអាចប្រើប្រាស់មីក្រូហ្វូនបានទេ។ សូមអនុញ្ញាតសិទ្ធិប្រើប្រាស់មីក្រូហ្វូនក្នុងកម្មវិធីរុករក ហើយព្យាយាមម្តងទៀត។',
      recordingUnsupported: 'កម្មវិធីរុករកនេះមិនគាំទ្រការថតសំឡេងទេ។ សូមប្រើប្រាស់ Chrome, Edge, Safari ឬ Firefox ជំនាន់ចុងក្រោយ។',
      recordingFailed: 'មិនអាចបម្លែងសំឡេងថតទៅជា MP3 បានឡើយ។',
      filenameLabel: 'ឈ្មោះឯកសារ',
      editFilename: 'កែសម្រួលឈ្មោះឯកសារ',
      audioToolsNavigation: 'ការរុករកឧបករណ៍សំឡេង',
      closeMessage: 'បិទសារជូនដំណឹង',
      removeFile: 'លុបចេញ',
      removeSelectedFiles: 'លុបឯកសារដែលបានជ្រើសរើសចេញ',
      prefixPlaceholder: 'មិនទាមទារ ឧ. khm_EBC_',
      chooseFolderRegion: 'ជ្រើសរើសថត (Folder)',
      audioSummary: 'ទិន្នន័យសង្ខេប',
      nonWavFiles: 'ឯកសារមិនមែន WAV',
      convertAllToWav: 'បម្លែងទាំងអស់ទៅជា WAV',
      exportCsvTitle: 'ទាញយករបាយការណ៍លម្អិតជាទម្រង់ CSV',
      selectWavFilesFromFiles: 'សូមជ្រើសរើសឯកសារ WAV ពីកម្មវិធី Files។',
      selectAudioFilesFromFiles: 'នៅក្នុង Voice Memos សូមចុច Share > Save to Files រួចជ្រើសរើសឯកសារ M4A ឬ MP3 នៅទីនេះ។',
      iosGuideLabel: 'ការណែនាំសម្រាប់ IPHONE',
      iosGuideTitle: 'វិធីផ្ទេរសំឡេងថតពី Voice Memos ទៅកាន់កម្មវិធី Files',
      iosGuideText: 'នៅក្នុងកម្មវិធី Voice Memos សូមជ្រើសរើសសំឡេងដែលបានថត រួចចុច Share > ជ្រើសរើស Save to Files និងរក្សាទុកក្នុងថត (Folder) ដែលអ្នកចង់បាន។',
      iosGuideButton: 'ជ្រើសរើសពី Files',
      iosGuideStepOne: '១. ចុចប៊ូតុង Share',
      iosGuideStepTwo: '២. ជ្រើសរើស Save to Files',
      iosGuideSteps: 'ជំហាន Voice Memos លើ iPhone',
      iosGuideStepOneText: 'បើកសំឡេងថតក្នុង Voice Memos រួចចុចលើប៊ូតុង Share។',
      iosGuideStepTwoText: 'រក្សាទុកឯកសារសំឡេងក្នុងថតណាមួយក្នុងកម្មវិធី Files។',
      iosGuideStepThree: '៣. បង្កើតថត (Folder) ថ្មី',
      iosGuideStepThreeText: 'ចុចលើពាក្យ New Folder នៅលើផ្ទាំងរក្សាទុក។',
      iosGuideStepFour: '៤. ដាក់ឈ្មោះថត',
      iosGuideStepFourText: 'វាយបញ្ចូលឈ្មោះសម្រាប់ថតថ្មីរបស់អ្នក។',
      iosGuideStepFive: '៥. ចូលទៅកាន់ថតនោះ',
      iosGuideStepFiveText: 'ចុចបើកថតដែលអ្នកទើបតែបានបង្កើត។',
      iosGuideStepSix: '៦. ចុចរក្សាទុក (Save)',
      iosGuideStepSixText: 'ចុចប៊ូតុង Save ដើម្បីរក្សាទុកឯកសារសំឡេងជាការស្រេច។',
      iosGuideReady: 'នៅពេលរក្សាទុករួចរាល់ សូមជ្រើសរើសឯកសារនៅទីនេះ។',
      iosGuideBack: 'ត្រឡប់ទៅទំព័របម្លែង',
      openingConverter: 'កំពុងបើកទំព័របម្លែង...',
      clearFiles: 'លុបឯកសារដែលបានជ្រើសរើស',
      audioTools: 'ឧបករណ៍សំឡេង',
      ffmpegLocal: 'ដំណើរការក្នុងឧបករណ៍ផ្ទាល់ · FFMPEG.WASM',
      addedBefore: 'បន្ថែមនៅខាងមុខឈ្មោះឯកសារ WAV',
      durationTitle: 'គណនារយៈពេលសរុបនៃឯកសារសំឡេង។',
      durationLede: 'ជ្រើសរើសថត (Folder) ដើម្បីគណនារយៈពេលសរុបនៃឯកសារ WAV ទាំងអស់ រួមទាំងថតរងខាងក្នុងផងដែរ។',
      selectFolder: 'ជ្រើសរើសថត (Folder) ផ្ទុកឯកសារ',
      privacyNote: 'ឯកសារទាំងអស់ដំណើរការក្នុងឧបករណ៍របស់អ្នក ដោយមិនមានការបង្ហោះឡើងលើអ៊ីនធឺណិតឡើយ។',
      dropWavFiles: 'ទម្លាក់ឯកសារ WAV នៅទីនេះ',
      chooseFolder: 'ជ្រើសរើសថត',
      totalDuration: 'រយៈពេលសរុប',
      successfulWav: 'ឯកសារ WAV ត្រឹមត្រូវ',
      unsuccessfulFiles: 'ឯកសារមិនត្រឹមត្រូវ',
      shortestFile: 'ឯកសារខ្លីជាងគេ',
      longestFile: 'ឯកសារវែងជាងគេ',
      totalSize: 'ទំហំសរុប',
      fileLedger: 'បញ្ជីឯកសារលម្អិត',
      noFilesScanned: 'មិនទាន់មានឯកសារស្កេន',
      exportCsv: 'ទាញយកជា CSV',
      emptyLedger: 'សូមជ្រើសរើសថត (Folder) ដើម្បីពិនិត្យមើលបញ្ជីឯកសារ WAV នៅទីនេះ។',
      showNonWav: 'បង្ហាញឯកសារដែលមិនមែន WAV',
      hideNonWav: 'លាក់ឯកសារដែលមិនមែន WAV',
      convertAll: 'បម្លែងទាំងអស់',
      scanComplete: 'ការស្កេនបានបញ្ចប់។ ឯកសារ WAV ទាំងអស់ត្រូវបានអានរួចរាល់។',
      noWavFound: 'រកមិនឃើញឯកសារ WAV នៅក្នុងថតនេះឡើយ។',
      localProcessing: 'ដំណើរការក្នុងឧបករណ៍',
      downloaded: 'បានទាញយក',
      tryAgain: 'ព្យាយាមម្តងទៀត',
      download: 'ទាញយក',
      packaging: 'កំពុងរៀបចំឯកសារ ZIP...',
      converting: 'កំពុងបម្លែង...',
      loadingFfmpeg: 'កំពុងដំណើរការ FFmpeg សម្រាប់ឯកសារ',
      conversionComplete: 'ការបម្លែងបានបញ្ចប់ដោយជោគជ័យ',
      conversionCompleteSkipped: 'ការបម្លែងបានបញ្ចប់ (មានឯកសារខ្លះមិនអាចបម្លែងបាន)',
      skipped: 'មិនបានបម្លែង',
      conversionFailed: 'ការបម្លែងមិនជោគជ័យឡើយ',
      noFilesConverted: 'មិនអាចបម្លែងឯកសារបានទេ។ សូមពិនិត្យមើលឯកសារសំឡេងរបស់អ្នកឡើងវិញ។',
      tooLarge: 'មានទំហំលើសពីកម្រិតកំណត់ 500 MB។',
      chooseSupported: 'សូមជ្រើសរើសតែឯកសារប្រភេទ M4A ឬ MP3។',
      unsupportedFiles: 'ឯកសារមិនគាំទ្រត្រូវបានដកចេញ',
      moreFiles: 'ឯកសារទៀត',
      unableFolder: 'មិនអាចបើកអានថតឯកសារនោះបានឡើយ។',
      showAllFiles: 'បង្ហាញឯកសារទាំងអស់',
      hideAllFiles: 'លាក់ឯកសារទាំងអស់',
      packageFailed: 'មិនអាចបង្កើតឯកសារ ZIP បានឡើយ។',
      couldNotConvert: 'មិនអាចបម្លែងបានឡើយ។',
      fileHeader: 'ឈ្មោះឯកសារ',
      durationHeader: 'រយៈពេល',
      reading: 'កំពុងអាន...',
      couldNotRead: 'មិនអាចអានបាន',
      waitingFolder: 'រង់ចាំការជ្រើសរើសថតឯកសារ...',
      readableOf: 'ក្នុងចំណោម',
      wavFile: 'ឯកសារ WAV',
      restored: 'បានស្ដារទិន្នន័យ',
      exported: 'បានទាញយករួចរាល់',
      unreadable: 'ឯកសារមិនអាចអានបាន',
      ready: 'រួចរាល់',
      fromBrowser: 'ពីកម្មវិធីរុករកនេះ',
      result: 'លទ្ធផល',
      results: 'លទ្ធផល',
      estimatedFor: 'ពេលវេលាប៉ាន់ស្មានសម្រាប់',
      recommendedBatch: 'ចំនួនណែនាំបម្លែងក្នុងមួយលើក',
      estimatedTime: 'ប្រហែល',
      remaining: 'នៅសល់',
      complete: 'រួចរាល់'
    }
  };

  function applyLanguage(language) {
    const selectedLanguage = language === 'kh' ? 'kh' : 'en';
    document.documentElement.lang = selectedLanguage === 'kh' ? 'km' : 'en';
    const pageTitleKey = location.pathname.endsWith('duration.html') ? 'durationPageTitle' : location.pathname.endsWith('recorder.html') ? 'recorderPageTitle' : location.pathname.endsWith('ios-guide.html') ? 'iosGuidePageTitle' : location.pathname.endsWith('404.html') ? 'errorPageTitle' : 'converterPageTitle';
    document.title = translations[selectedLanguage][pageTitleKey];
    document.querySelectorAll('[data-i18n]').forEach((element) => {
      const value = translations[selectedLanguage][element.dataset.i18n];
      if (value) element.textContent = value;
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach((element) => {
      const value = translations[selectedLanguage][element.dataset.i18nPlaceholder];
      if (value) element.placeholder = value;
    });
    document.querySelectorAll('[data-i18n-aria-label]').forEach((element) => {
      const value = translations[selectedLanguage][element.dataset.i18nAriaLabel];
      if (value) element.setAttribute('aria-label', value);
    });
    // [data-i18n-title] is reserved for future tooltip translation — no elements
    // currently use this attribute, so the query is a no-op. Kept for forward compatibility.
    document.querySelectorAll('[data-i18n-title]').forEach((element) => {
      const value = translations[selectedLanguage][element.dataset.i18nTitle];
      if (value) element.title = value;
    });
    document.querySelectorAll('.lang-toggle').forEach((button) => {
      button.setAttribute('aria-pressed', String(selectedLanguage === 'kh'));
      button.querySelector('[data-lang="en"]').classList.toggle('active', selectedLanguage === 'en');
      button.querySelector('[data-lang="kh"]').classList.toggle('active', selectedLanguage === 'kh');
    });
    localStorage.setItem('wavecraft-language', selectedLanguage);
    window.dispatchEvent(new CustomEvent('wavecraft:language', { detail: { language: selectedLanguage, translations: translations[selectedLanguage] } }));
  }

  document.addEventListener('DOMContentLoaded', () => {
    const initialLanguage = localStorage.getItem('wavecraft-language') || 'en';
    document.querySelectorAll('.lang-toggle').forEach((button) => {
      button.addEventListener('click', () => {
        // Read the current language from localStorage rather than the closure
        // value so it stays correct if applyLanguage() was called programmatically.
        const currentLanguage = localStorage.getItem('wavecraft-language') || 'en';
        applyLanguage(currentLanguage === 'en' ? 'kh' : 'en');
      });
    });
    document.querySelectorAll('.nav-menu-button').forEach((button) => {
      button.addEventListener('click', () => {
        const navigation = button.closest('.app-nav');
        const expanded = navigation.classList.toggle('menu-open');
        button.setAttribute('aria-expanded', String(expanded));
      });
    });
    document.querySelectorAll('.nav-links a').forEach((link) => {
      link.addEventListener('click', () => {
        const navigation = link.closest('.app-nav');
        const button = navigation?.querySelector('.nav-menu-button');
        navigation?.classList.remove('menu-open');
        button?.setAttribute('aria-expanded', 'false');
      });
    });
    applyLanguage(initialLanguage);
  });
})();
